- doc/changes/changes_0.2.0.md
- pom.xml
- src/main/java/com/exasol/adapter/document/files/S3Uri.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
- src/test/resources/simpleMapping.json
> #6: Improved errors message for wrong connection strings

- .github/workflows/release_droid_prepare_original_checksum.yml
- doc/changes/changes_1.1.0.md
- pom.xml
> bug/23: Fixed failing release automation

- doc/changes/changelog.md
- doc/changes/changes_1.3.0.md
- doc/hands_on/hands_on.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/adapter/document/files/S3Uri.java
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
> bug/27: Fixed sonar security hotspot

- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_1.3.0.md
- doc/hands_on/hands_on.md
- doc/user_guide/user_guide.md
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
> Dependency updates

- .ci/retry.sh
- .ci/upload_regression_test_result.sh
- .github/workflows/manual_run_regression_tests.yml
- doc/changes/changes_1.5.0.md
> bug/47: Fixed upload of regression test results

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- doc/changes/changes_1.6.0.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
> Prepared release 1.6.0

- README.md
Added third party notice to redme
> Added third party notice to redme

- doc/changes/changes_1.7.0.md
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
Closes #62 
The fix was already part of #65. This PR just adjusted the tests.
> bug/62: Fixed support for dots in bucket name

- doc/changes/changelog.md
- doc/changes/changes_2.0.0.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pom.xml
- src/main/java/com/exasol/adapter/document/files/S3ClientFactory.java
- src/main/java/com/exasol/adapter/document/files/S3FileLoader.java
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
> feature/59: Added support for path-style syntax

- doc/changes/changelog.md
- doc/changes/changes_2.0.1.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
> bug/68: Fixed broken regression test

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_check.yml
- .github/workflows/manual_run_regression_tests.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- .github/workflows/release_droid_print_quick_checksum.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.1.1.md
- doc/developers_guide/developers_guide.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3Cache.java
- src/test/java/com/exasol/adapter/document/files/S3DirectUploader.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
- src/test/java/com/exasol/adapter/document/files/S3UploadInterface.java
- src/test/java/com/exasol/adapter/document/files/TestConfig.java
> feature/76: Made cache bucket name configurable

- doc/changes/changelog.md
- doc/changes/changes_2.3.0.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
https://github.com/exasol/virtual-schema-common-document-files/issues/109
> CSV support

- extension/src/addInstance.ts
- extension/src/extension.test.ts
- extension/src/installExtension.ts
See https://github.com/exasol/extension-manager/issues/49
> Adapt extension transaction handling

- .gitattributes
- .github/workflows/ci-build.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- dependencies.md
- doc/changes/changes_2.4.0.md
- doc/developers_guide/developers_guide.md
- extension/package-lock.json
- extension/package.json
- extension/src/extension.ts
- extension/src/findInstallations.ts
- extension/src/installExtension.ts
- extension/tsconfig.json
- pk_generated_parent.pom
- pom.xml
- release_config.yml
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/extension/ExtensionIT.java
- src/test/java/com/exasol/adapter/document/files/extension/ExtensionManagerClient.java
- src/test/java/com/exasol/adapter/document/files/extension/installer/InstallerFromGitHub.java
- src/test/java/com/exasol/adapter/document/files/extension/installer/InstallerFromLocalFolder.java
- src/test/java/com/exasol/adapter/document/files/extension/process/SimpleProcess.java
- src/test/resources/extension-manager-swagger.yaml
Adapt to new api as defined in https://github.com/exasol/extension-manager/issues/55
> Adapt to new api

- .project-keeper.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.4.2.md
- doc/developers_guide/developers_guide.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- error_code_config.yml
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/adapter/document/files/RequestRateRetryIterator.java
- src/main/java/com/exasol/adapter/document/files/connection/S3ConnectionPropertiesReader.java
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/RequestRateRetryIteratorTest.java
- src/test/java/com/exasol/adapter/document/files/S3Cache.java
- src/test/java/com/exasol/adapter/document/files/TestConfig.java
- src/test/java/com/exasol/adapter/document/files/connection/S3ConnectionPropertiesReaderTest.java
- src/test/java/com/exasol/adapter/document/files/extension/ExtensionIT.java
fixes #103 
fixes #97 
fixes #98
> Fixed vulnerabilities

- .project-keeper.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.5.0.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
> #108: Auto-inference for Parquet files

- .ci/upload_regression_test_result.sh
- .gitattributes
- .github/workflows/manual_run_regression_tests.yml
- .settings/org.eclipse.m2e.core.prefs
- cloudSetup/.gitignore
- cloudSetup/.terraform.lock.hcl
- cloudSetup/cloudSetup.tf
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.5.1.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
> #112: Fix performance regression tests

- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_2.6.0.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3Cache.java
> #116: Added automatic schema inference for CSV files

- .github/workflows/manual_run_regression_tests.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- ci-isolation/src/main/resources/exasol-permissions.json
- doc/changes/changelog.md
- doc/changes/changes_2.6.1.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
> #118: Use data types in CSV performance regression tests

- cloudSetup/variables.tf
- doc/changes/changelog.md
- doc/changes/changes_2.8.1.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_minio.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
> #132 Fix wording in hands-on-guide for Minio

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/ci_isolation_ci_build.yml
- .github/workflows/dependencies_check.yml
- .github/workflows/manual_run_regression_tests.yml
- .github/workflows/release_droid_prepare_original_checksum.yml
- .github/workflows/release_droid_print_quick_checksum.yml
- .github/workflows/release_droid_upload_github_release_assets.yml
- .project-keeper.yml
- dependencies.md
- doc/changes/changes_2.8.1.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- extension/src/addInstance.ts
- extension/src/common.ts
- extension/src/extension.test.ts
- extension/src/extension.ts
- extension/src/installExtension.ts
- extension/src/upgrade.test.ts
- pom.xml
- src/main/resources/classes.lst
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/extension/ExtensionIT.java
> #135: Fix CVE-2023-43642, CVE-2023-42503 & CVE-2023-4759

- .github/workflows/manual_run_regression_tests.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.0.1.md
- doc/changes/changes_3.0.2.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- extension/package-lock.json
- extension/package.json
- extension/src/extension.ts
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
- src/test/java/com/exasol/adapter/document/files/extension/ExtensionIT.java
> #143: Fix performance regression tests

- .github/workflows/broken_links_checker.yml
- .github/workflows/ci-build-next-java.yml
- .github/workflows/ci-build.yml
- .github/workflows/dependencies_update.yml
- dependencies.md
- doc/changes/changelog.md
- doc/changes/changes_3.0.7.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
> Security update - fix for CVE-2024-36114

- .github/workflows/ci-build.yml
- .project-keeper.yml
- doc/changes/changelog.md
- doc/changes/changes_3.1.1.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- extension/package-lock.json
- extension/package.json
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3DocumentFilesAdapterIT.java
- src/test/java/com/exasol/adapter/document/files/extension/ExtensionIT.java
> #170: Upgrade dependencies

- .github/workflows/ci-build.yml
- .settings/org.eclipse.jdt.core.prefs
- SECURITY.md
- doc/changes/changelog.md
- doc/changes/changes_3.1.4.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/adapter/document/files/S3ClientFactory.java
- src/main/java/com/exasol/adapter/document/files/connection/S3ConnectionProperties.java
- src/main/java/com/exasol/adapter/document/files/connection/S3ConnectionPropertiesReader.java
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/connection/S3ConnectionPropertiesReaderTest.java
- src/test/resources/logging.properties
> Public S3 buckets support

- .github/workflows/ci-build.yml
- .github/workflows/dependencies_update.yml
- .github/workflows/release.yml
- doc/changes/changelog.md
- doc/changes/changes_3.1.7.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/main/java/com/exasol/adapter/document/files/S3FileFinder.java
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
- src/test/java/com/exasol/adapter/document/files/S3FileFinderTest.java
> Added more logging around the paths that lead to the creation of the query plan.

- .github/workflows/dependencies_check.yml
- doc/changes/changelog.md
- doc/changes/changes_3.1.8.md
- doc/hands_on/hands_on.md
- doc/hands_on/hands_on_parquet.md
- doc/user_guide/user_guide.md
- pk_generated_parent.pom
- pom.xml
- src/test/java/com/exasol/adapter/document/files/IntegrationTestSetup.java
>  Fixes for vulnerabilities CVE-2025-48924 and CVE-2025-55163
